name: Main CI
on: [push, pull_request]
jobs:
  build:
    name: Build Test
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ui

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup node environment
        uses: actions/setup-node@v2
        with:
          node-version: 20.x
      - name: Get pnpm cache directory path
        id: pnpm-cache-dir-path
        run: echo "::set-output name=dir::$(pnpm config get store-dir)"
      - uses: actions/cache@v2
        id: pnpm-cache # use this to check for `cache-hit` (`steps.pnpm-cache.outputs.cache-hit != 'true'`)
        with:
          path: ${{ steps.pnpm-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
              ${{ runner.os }}-pnpm-
      - name: Install deps
        run: pnpm install --frozen-lockfile
      - name: Try build
        run: pnpm build
