name: Discord release notification

on:
  release:
    types: [published]

jobs:
  notify:
    uses: Red40-Development/red40-public-workflows/.github/workflows/discord-release.yml@v1
    with:
      avatar_url: "https://slrn.dev/SLRN_Development.png"
      footer_icon_url: "https://slrn.dev/SLRN_Development.png"
      footer_title: "SLRN Development"
    secrets:
      DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
