name: Discord commit notification

on:
  push:
    branches: [main]

jobs:
  notify:
    uses: Red40-Development/red40-public-workflows/.github/workflows/discord-push.yml@v1
    secrets:
      DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
