name: Lint

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

permissions:
  contents: read
  checks: write

jobs:
  lint:
    uses: Red40-Development/red40-public-workflows/.github/workflows/lint.yml@v1
